### ISSUE TITLE
中翻英 未返回翻译结果

### ISSUE THREAD

**Issue by AjianNie** [akl7777777/bob-plugin-akl-youdao-free-translate#4]
非本地启动服务版本 有道翻译插件，忘记之前有道翻译是否可以 中翻英，今天发现不行——显示“接口未返回翻译结果”。
插件版本：最新 v 0.1.8
网络：直连/挂梯 都不行
版本：商店版 1.8.2 ; intel macOS13.6

**Comment by AjianNie** [comment]
很奇怪，自己恢复正常了 hhh

**Comment by Shenfq** [comment]
我这里也有这个问题
<img width="400" alt="image" src="https://github.com/akl7777777/bob-plugin-akl-youdao-free-translate/assets/18613842/4b8114a3-9e96-4e60-af69-3b0f66e85033">

**Comment by AjianNie** [comment]
> 我这里也有这个问题 <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/18613842/292059914-4b8114a3-9e96-4e60-af69-3b0f66e85033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTg1NzcsIm5iZiI6MTcwMzE1ODI3NywicGF0aCI6Ii8xODYxMzg0Mi8yOTIwNTk5MTQtNGI4MTE0YTMtOWU5Ni00ZTYwLWFmNjktM2IwZjY2ZTg1MDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDExMzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZTM3NDdkYjJiYmFmM2RhZDgxNTM2MTdiYjhmOWQ1N2Y2NmY5MTFhMzA5ZDg1M2Q4NTg5NDNkOWRhNjgwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZ3jsJulAaCdbYoLSe-01maESWUy1jQtmqpZ8GHf-pE">

确实单词短语容易触发这个问题。
既然有人也遇到这个问题，我暂时重启 issue，看看作者态度。

**Comment by akl7777777** [comment]
已修复,请更新0.2.0
