### ISSUE TITLE
翻译句子时，接口未返回翻译结果，单个单词可以

### ISSUE THREAD

**Issue by JamesW99** [akl7777777/bob-plugin-akl-youdao-free-translate#5]
<img width="396" alt="image" src="https://github.com/akl7777777/bob-plugin-akl-youdao-free-translate/assets/44286680/d26e58a3-22fb-434e-a41e-ce947ef1890c">

**Comment by Jagerx** [comment]
故障相同

**Comment by akl7777777** [comment]
先用依赖服务版,我试过没问题,免服务版等我修复
<img width="1425" alt="image" src="https://github.com/akl7777777/bob-plugin-akl-youdao-free-translate/assets/84266551/634ccfc9-8e74-4034-905d-f7f52f2b779e">

**Comment by akl7777777** [comment]
> 故障相同

已修复,请更新0.2.0
